from snakemake.utils import min_version


# Configuration
configfile: "config/config.yaml"


# Settings
min_version("7.32.4")


# Modules
module genome:
    snakefile:
        "rules/genome.smk"
    config:
        config["GENOME"]

module gencode:
    snakefile:
        "rules/gencode.smk"
    config:
        config["GENCODE"]


# Import modules
use rule * from genome as genome_*
use rule * from gencode as gencode_*


###
# Rules
###


rule all:
    message:
        """
        DEPLOYING GENOME...
        """
    input:
        rules.genome_all.input,
        rules.gencode_all.input,
